### ISSUE TITLE
remoteHelper throws on git ssh urls

### ISSUE THREAD

**Issue by losnappas** [phoihos/vscode-git-commit-message-editor#3]
Hi, nice work with the scopes, it works nicely.

I came across this bug with repositories cloned via ssh, where this line https://github.com/phoihos/vscode-git-commit-message-editor/blob/42ea0f2a07f8d4844ec85bcde94b398e3611b5fe/src/gitService/remoteHelper.ts#L55 throws an error, because the `url` is of the form `'git@gitlab.whatever.com:user/repository-name'`, which isn't valid for `vscode.Uri.parse` and then that throws `'[UriError]: Scheme contains illegal characters.'`

Ex. if you clone this repo with `git clone git@github.com:phoihos/vscode-git-commit-message-editor.git`, then the code lens and scope suggestions break.

**Comment by phoihos** [comment]
I fixed this issue and released new version 0.6.1.
Thank you for your reporting.
